
# Random Variables Definition
random_variables:
  grid_size_x: "random.choice([5])"
  grid_size_y: "random.choice([2])"
  computed_size_x: "grid_size_x - 1"
  computed_size_y: "grid_size_y- 1"

env_variables:
  corner_positions:
    - [0, 0]                          # South-West Corner
    - [0, grid_size_x - 1]            # South-East Corner
    - [grid_size_y - 1, 0]            # North-West Corner
    - [grid_size_y - 1, grid_size_x - 1]  # North-East Corner

max_episodes: 10
num_agents: 4
grid_size: [grid_size_x, grid_size_y]  # If no value is specified, default grid size of (5,5) is used.

actions: |
  - **north**
  - **south**
  - **west**
  - **east**
  - **skip**

# Unified Goal for Each Agent
unified_goal: |
  Goal: Form Alphabetical Line
  
  Coordinate positions based on agent names in alphabetical order
  Form single line starting at (0, 0), extending right at y=0
  Confirm positions with all agents before moving
  Example: For [Charlie, Alpha, Beta]
  
  Alpha -> (0, 0)
  Beta -> (1, 0)
  Charlie -> (2, 0)
