# Random Variables Definition
random_variables:
  grid_size_x: "random.choice([4, 5, 6])"
  grid_size_y: "random.choice([4, 5, 6])"
  computed_size_x: "grid_size_x - 1"
  computed_size_y: "grid_size_y- 1"

env_variables:
  corner_positions:
    - [0, 0]                          # South-West Corner
    - [0, computed_size_x ]            # South-East Corner
    - [computed_size_y, 0 ]            # North-West Corner
    - [computed_size_y, computed_size_x]  # North-East Corner

max_episodes: 10
num_agents: 4
grid_size: [grid_size_y, grid_size_x]  # If no value is specified, default grid size of (5,5) is used.

actions: |
  - **north**
  - **south**
  - **west**
  - **east**
  - **skip**


# Unified Goal for Each Agent
unified_goal: |
  Your goal is for each agent to reach an independent corner of the grid without sharing it with another agent. Your specific target position must be one of the following:
  - South-West Corner: (0, 0)
  - South-East Corner: (0, computed_size_x)
  - North-West Corner: (computed_size_y, 0)
  - North-East Corner: (computed_size_y, computed_size_x)

  Initially, communicate with other agents to decide who will occupy which corner. Only start moving once all agents have agreed on unique corners to avoid conflicts.

  ***IMPORTANT***:
  - **Verification**: Continuously verify your progress by checking the current score.
  - **Reflection**: If the score is not 100/100, reflect on possible reasons and discuss with other agents to resolve any issues.
  - **Collaboration**: Work together to ensure all agents reach their assigned corners.

  You must reach a score of 100/100 for the successful completion of the simulation.

  **IMPORTANT**: Corners have a "target" item in them. Use this to verify you are in a corner


# OPTIONAL PROMPTS. USE THESE TO OVERRIDE THE EXISTING PROMPTS
system_prompt: NONE
user_prompt: NONE
