# Random Variables Definition
random_variables:
  grid_size_x: "random.choice([4, 5, 6])"
  grid_size_y: "random.choice([4, 5, 6])"
  computed_size_x: "grid_size_x - 1"
  computed_size_y: "grid_size_y - 1"
  num_agents: "random.choice([3])"
  all_positions: "[(y,x) for y in range(grid_size_y) for x in range(grid_size_x)]"
  target_positions: "random.sample(all_positions, num_agents)"

env_variables:
 target_positions: target_positions
 computed_size_y: computed_size_y
 computed_size_x: computed_size_x

max_episodes: 10
num_agents: num_agents
grid_size: [grid_size_x, grid_size_y]

actions: |
  - **north**
  - **south**
  - **west**
  - **east**
  - **skip**


# Unified Goal for Each Agent
unified_goal: |
  Your goal is to search the grid and find unoccupied positions with a "target" item in it. You will be notified if there are items in your current square.  
  The simulation ends successfully when each agent occupies a unique position with a target item (score 100/100).


# OPTIONAL PROMPTS. USE THESE TO OVERRIDE THE EXISTING PROMPTS
system_prompt: NONE
prompt: NONE
user_prompt: NONE