random_variables:
  grid_size_x: "random.choice([4, 5, 6])"
  grid_size_y: "random.choice([4, 5, 6])"
  target_x: "random.randint(0, grid_size_x - 1)"
  target_y: "random.randint(0, grid_size_y - 1)"
  item_positions: "random.sample([(y, x) for y in range(grid_size_y) for x in range(grid_size_x)], 1)"

env_variables:
  target_position: [target_y, target_x]
  item_positions: item_positions

max_episodes: 10
num_agents: 1
grid_size: [grid_size_y, grid_size_x]

actions: |
  - **north**
  - **south**
  - **west**
  - **east**
  - **pick**
  - **drop**

unified_goal: |
  PRIMARY GOAL: Pick up all items and reach position [target_y, target_x].

output_instruction_text: |
  You are required to respond in JSON format only.

  Your response must include the following keys:
  1. **action_name**: The name of the action you intend to perform.
  2. **action_parameters**: Any specific parameters related to the action, such as step count or target position. If there are no parameters, use an empty dictionary.
  3. **rationale**: A brief explanation of why this action was chosen, considering the current state and objectives.

  Here is an example of the expected format:

  {
    "action_name": "north",
    "action_parameters": {"steps": 1},
    "rationale": "Moving up to get closer to the target position."
  }

  Remember, you must always output a JSON response following this structure.