# Random Variables Definition
random_variables:
  grid_size_x: "random.choice([4, 5, 6])"
  grid_size_y: "random.choice([4, 5, 6])"
  target_x: "random.randint(0, grid_size_x - 1)"
  target_y: "random.randint(0, grid_size_y - 1)"

env_variables:
  target_position: [target_x, target_y]

max_episodes: 10
num_agents: 1
grid_size: [grid_size_x, grid_size_y]    # If no value is specified, default grid size of (5,5) is used.

actions: |
  - **north**
  - **south**
  - **west**
  - **east**

# Specify target clearly here.
unified_goal: |
  PRIMARY GOAL: Reach position [target_x, target_y]. This is when your x position is target_x, and y position is target_y.
  Use your observations to determine the exact corner coordinates.
