random_variables:
  grid_size_x: "random.choice([3, 4, 5])"
  grid_size_y: "random.choice([3, 4, 5])"
  computed_size_x: "grid_size_x - 1"
  computed_size_y: "grid_size_y - 1"
  target_x: "random.randint(0, grid_size_x - 1)"
  target_y: "random.randint(0, grid_size_y - 1)"
  item_positions: "random.sample([(x, y) for y in range(grid_size_y) for x in range(grid_size_x)], 1)"
  target_positions: "random.sample([(x, y) for y in range(grid_size_y) for x in range(grid_size_x)], 1)"

env_variables:
  target_positions: target_positions
  item_positions: item_positions

max_episodes: 15
num_agents: 1
grid_size: [grid_size_x, grid_size_y]

actions: |
  - **north**
  - **south**
  - **west**
  - **east**
  - **pick**
  - **drop**

unified_goal: |
  PRIMARY GOAL: 
  First pick up item at item_positions. Then verify and memorize the item is picked up successfully. Finally go to target position target_positions and drop off the item.